sonar.projectKey=AGV48_Encuentros-Front
sonar.organization=agv48
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/encuentros-front/lcov.info
sonar.typescript.lcov.reportPaths=coverage/encuentros-front/lcov.info
sonar.coverage.exclusions=**/*.spec.ts,**/*.module.ts,src/main.ts,src/polyfills.ts,src/test.ts
